import type { WorkOrder, Station, AIInsight, KPIs } from "./types";

export const mockKpis: KPIs = {
  unitsProduced: 187,
  unitsPlanned: 240,
  qcFailures: 14,
  failureRate: 7.5,
  avgCycleTime: 38,
  cycleTimeTarget: 32,
  activeWorkOrders: 9,
};

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "mock-wo-1",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0051",
    customer_name: "Siemens AG",
    part_number: "PCB Control Unit",
    planned_qty: 240,
    actual_qty: 187,
    units_scrapped: 0,
    status: "wip",
    priority: "high",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-25",
    created_at: new Date().toISOString(),
    line_id: "Line 1",
  },
  {
    id: "mock-wo-2",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0052",
    customer_name: "Bosch GmbH",
    part_number: "Motor Driver Board",
    planned_qty: 150,
    actual_qty: 142,
    units_scrapped: 0,
    status: "qc",
    priority: "medium",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-24",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-3",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0053",
    customer_name: "CONTAG AG",
    part_number: "Sensor Interface",
    planned_qty: 80,
    actual_qty: 80,
    units_scrapped: 0,
    status: "done",
    priority: "low",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-23",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-4",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0054",
    customer_name: "Eolane SysCom",
    part_number: "RF Amplifier Module",
    planned_qty: 200,
    actual_qty: 61,
    units_scrapped: 0,
    status: "delayed",
    priority: "urgent",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-23",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-5",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0055",
    customer_name: "Daimler AG",
    part_number: "CAN Bus Controller",
    planned_qty: 120,
    actual_qty: 0,
    units_scrapped: 0,
    status: "planned",
    priority: "medium",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-26",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-6",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0056",
    customer_name: "CYBERTRON GmbH",
    part_number: "Kinematic Servo Board",
    planned_qty: 60,
    actual_qty: 38,
    units_scrapped: 0,
    status: "wip",
    priority: "high",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-27",
    created_at: new Date().toISOString(),
  },
];

export const mockStations: Station[] = [
  { name: "SMT", cycleTime: 5.2, target: 5.0, qcFailures: 1, isBottleneck: false },
  { name: "Soldering", cycleTime: 6.1, target: 5.5, qcFailures: 2, isBottleneck: false },
  { name: "Visual Inspection", cycleTime: 14.8, target: 6.4, qcFailures: 11, isBottleneck: true },
  { name: "Functional Test", cycleTime: 7.3, target: 7.0, qcFailures: 0, isBottleneck: false },
  { name: "Packaging", cycleTime: 4.4, target: 4.5, qcFailures: 0, isBottleneck: false },
];

export const mockInsights: AIInsight[] = [
  {
    type: "critical",
    title: "Bottleneck: Visual Inspection",
    body: "Average dwell time 14.8 min vs 6.4 min target. 11 of 14 QC failures (79%) originated here. At current throughput you will finish the shift at 211 units vs 240 planned. Assigning a second operator is the highest-impact action available.",
    time: "2 min ago",
  },
  {
    type: "warning",
    title: "WO-2024-0054 at risk of missing deadline",
    body: "RF Amplifier Module (Eolane SysCom) is at 30% completion with a same-day deadline. Current pace projects completion at 21:40 — 3 hours after shift end.",
    time: "8 min ago",
  },
  {
    type: "warning",
    title: "QC failure rate above threshold",
    body: "7.5% failure rate today vs 3.2% weekly average. 11 of 14 failures are concentrated at Visual Inspection — likely an operator or lighting issue, not a component defect.",
    time: "15 min ago",
  },
  {
    type: "info",
    title: "Plan attainment trending down",
    body: "Last 4 shifts: 94% → 91% → 87% → 78%. The decline correlates with the Visual Inspection bottleneck growing from 8.1 min to 14.8 min average cycle time.",
    time: "1 hr ago",
  },
  {
    type: "positive",
    title: "WO-2024-0053 completed ahead of schedule",
    body: "Sensor Interface (CONTAG AG) — 80 units completed 2.5 hours before deadline. Packaging station performed at 4.4 min avg cycle vs 4.5 target.",
    time: "2 hr ago",
  },
];
