import type { WorkOrder, Station, AIInsight, KPIs, PartKPIs } from "./types";

export const mockKpis: KPIs = {
  unitsProduced: 187,
  unitsPlanned: 240,
  qcFailures: 14,
  failureRate: 7.5,
  avgCycleTime: 38,
  cycleTimeTarget: 32,
  activeWorkOrders: 9,
};

export const mockPartKpis: PartKPIs = {
  partsInProduction: 33,
  releasedToday: 47,
  reworkFailed: 6,
  activeLines: 1,
};

export const mockWorkOrders: WorkOrder[] = [
  {
    id: "mock-wo-1",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0051",
    customer_name: "Siemens AG",
    part_number: "PCB Control Unit",
    planned_qty: 240,
    actual_qty: 187,
    units_scrapped: 0,
    status: "wip",
    priority: "high",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-25",
    created_at: new Date().toISOString(),
    line_id: "Line 1",
  },
  {
    id: "mock-wo-2",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0052",
    customer_name: "Bosch GmbH",
    part_number: "Motor Driver Board",
    planned_qty: 150,
    actual_qty: 142,
    units_scrapped: 0,
    status: "qc",
    priority: "medium",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-24",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-3",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0053",
    customer_name: "CONTAG AG",
    part_number: "Sensor Interface",
    planned_qty: 80,
    actual_qty: 80,
    units_scrapped: 0,
    status: "done",
    priority: "low",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-23",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-4",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0054",
    customer_name: "Eolane SysCom",
    part_number: "RF Amplifier Module",
    planned_qty: 200,
    actual_qty: 61,
    units_scrapped: 0,
    status: "delayed",
    priority: "urgent",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-23",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-5",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0055",
    customer_name: "Daimler AG",
    part_number: "CAN Bus Controller",
    planned_qty: 120,
    actual_qty: 0,
    units_scrapped: 0,
    status: "planned",
    priority: "medium",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-26",
    created_at: new Date().toISOString(),
  },
  {
    id: "mock-wo-6",
    tenant_id: "mock-tenant",
    wo_number: "WO-2024-0056",
    customer_name: "CYBERTRON GmbH",
    part_number: "Kinematic Servo Board",
    planned_qty: 60,
    actual_qty: 38,
    units_scrapped: 0,
    status: "wip",
    priority: "high",
    stations: ["SMT", "Soldering", "Visual Inspection", "Functional Test", "Packaging"],
    serial_tracking: false,
    due_date: "2024-04-27",
    created_at: new Date().toISOString(),
  },
];

export const mockStations: Station[] = [
  { name: "SMT", cycleTime: 5.2, target: 5.0, qcFailures: 1, isBottleneck: false },
  { name: "Soldering", cycleTime: 6.1, target: 5.5, qcFailures: 2, isBottleneck: false },
  { name: "Visual Inspection", cycleTime: 14.8, target: 6.4, qcFailures: 11, isBottleneck: true },
  { name: "Functional Test", cycleTime: 7.3, target: 7.0, qcFailures: 0, isBottleneck: false },
  { name: "Packaging", cycleTime: 4.4, target: 4.5, qcFailures: 0, isBottleneck: false },
];

export const mockInsights: AIInsight[] = [
  {
    type: "critical",
    title: "Bottleneck: Visual Inspection",
    detail: "Average dwell time 14.8 min vs 6.4 min target. 23 parts are queued here right now — the longest wait on Line A. At current pace, 31 fewer units will be released this shift.",
    action: "Assign a second operator to Visual Inspection",
  },
  {
    type: "critical",
    title: "4 parts stuck in Rework",
    detail: "4 parts have been flagged for rework with no scan activity in the last 90 minutes. If not resolved before shift end, they will roll into tomorrow's backlog.",
    action: "Check rework queue and reassign operator",
  },
  {
    type: "warning",
    title: "QC failure rate above threshold",
    detail: "2 parts failed QC today vs a 0.8% weekly average. Both failures originated at Soldering — likely a temperature or flux issue, not a component defect.",
    action: "Inspect Soldering station temperature log",
  },
  {
    type: "info",
    title: "6 parts at QC awaiting decision",
    detail: "6 parts are sitting at QC with no action recorded. Average wait time is 47 minutes. Clearing these would immediately free capacity at downstream stations.",
  },
  {
    type: "positive",
    title: "47 parts released — ahead of yesterday",
    detail: "Today's release count of 47 is 12% above yesterday's equivalent shift point. SMT and Crimping stations are both running within target cycle times.",
  },
];
